//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGSHOPNOMINA2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int IDtransacciones { get; set; }
        public int IDempleados { get; set; }
        public int Idingresoodeduccion { get; set; }
        public int IDtipodeducciones { get; set; }
        public int IDtiposdeingresos { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Tipodededucciones Tipodededucciones { get; set; }
        public virtual Tiposdeingresos Tiposdeingresos { get; set; }
    }
}
