//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int IdTransaccion { get; set; }
        public int IdTipoTransaccion { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdCliente { get; set; }
        public int NumeroDocumento { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
